version: 1

inputs:
  username:
    type: string
    description: user identifier
  password:
    type: string
    description: user password

stages:
- id: build
  type: ci
  spec:
    platform:
      os: linux
      arch: arm64
      variant: v7
    steps:
      - type: script
        spec:
          run: |-
            go build
            go test
        
      - type: plugin
        spec:
          image: plugins/docker
          with:
            repo: foo/bar
      - type: action
        spec:
          uses: foo/bar
          with:
            baz: qux